modLoader="javafml"
loaderVersion="[36,]"
issueTrackerURL="https://github.com/Darkhax/Minecraft-Modding-Template/issues"
license="LGPL v2.1"

[[mods]]
modId="examplemod"
updateJSONURL="https://updates.blamejared.com/get?n=examplemod&gv=1.16.5"
version="${version}"
displayName="${modName}"
displayURL="${modHomepage}"
credits="${modCredits}"
authors="${modAuthor}"
description='''
${modDescription}
'''

[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[36,]"
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"