modLoader="javafml"
loaderVersion="[37,]"
issueTrackerURL="https://github.com/Darkhax/Minecraft-Modding-Template/issues"
license="LGPL v2.1"
logoFile="mod_logo.png"
logoBlur=false

[[mods]]
modId="examplemod"
updateJSONURL="https://updates.blamejared.com/get?n=examplemod&gv=1.17.1"
version="${file.jarVersion}"
displayName="${modName}"
displayURL="${modHomepage}"
credits="${modCredits}"
authors="${modAuthor}"
description='''
${modDescription}
'''
itemIcon="minecraft:golden_apple"

[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[37,]"
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"